fix(intextcitation): Adding initial mark up and styles EHF-13722
evdy-consumer/component-react-in-text-citation pull request #1
Opened 2020-09-15 16:05 UTC by yasodaesarapu

2020-09-15 16:54 UTC, wsaun-edh approved these changes

2020-09-15 17:34 UTC, clucaseh requested changes
Please update your react-component-generator you are not using the latest code

2020-09-15 19:25 UTC, yasodaesarapu commented
> Please update your react-component-generator you are not using the latest code

Yes , i will update for my next component creation.

2020-09-16 14:24 UTC, clucaseh commented on src/index.js
> +          <img src={viewSourceIcon} alt="view source icon" className="in-text-citation__lightbox-verifiedsource-icon"/>
Please use img component with resizeOptions

2020-09-16 14:24 UTC, clucaseh commented on src/index.js
> +        className="in-text-citation__lightbox-viewsourceurl"
Why are we not using linkModel with rel passed

2020-09-16 14:24 UTC, clucaseh commented on src/index.js
> +    <button
Why are we not using new button component

2020-09-16 15:09 UTC, sblashkin commented on src/component.scss
> +      padding: 12px 15px 0 0;
I think we should use a spatial system for padding and margins

2020-09-16 15:41 UTC, yasodaesarapu commented
@clucaseh @sblashkin Will address your comments in new PR . Right now i am updating component with stories.

2020-09-16 15:41 UTC, closed without merging