fix(inTextCitation): Added unit tests and some markup changes EHF-13722
evdy-consumer/component-react-in-text-citation pull request #3
Opened 2020-09-18 15:32 UTC by yasodaesarapu

2020-09-18 15:49 UTC, MiSTERSPOONS commented on src/index.js
> +    closeLightBox(this.toggleLightBox());
Did you mean to:
```javascript
closeLightBox(this.toggleLightBox);
```
without the invocation? because `this.toggleLightBox` is just setting state to `displayLightBox`

2020-09-18 16:10 UTC, yasodaesarapu commented on src/index.js
> +    closeLightBox(this.toggleLightBox());
@MiSTERSPOONS without invocation toggleLightBox method isn't getting called.

2020-09-18 16:22 UTC, wsaun-edh commented on __tests__/src/index-test.js
> +    wrapper.setState({ hoverOnArrow: true });
would be a better test to simulate mouseOver and mouseLeave events

2020-09-18 16:23 UTC, MiSTERSPOONS commented on src/index.js
> +    closeLightBox(this.toggleLightBox());
@yasodaesarapu you would need to invoke it on the parent component, where you are passing down the `closeLightBox` prop

2020-09-18 16:26 UTC, wsaun-edh commented on __tests__/src/index-test.js
> +    const viewSourceiconURL = 'https://images.everydayhealth.com/react-component-images/badge.png';
may be good to use a different URL here since this is the default

2020-09-18 16:38 UTC, sblashkin commented
should **Arrow Directional** and **close button** have **cursor: pointer**?

2020-09-18 16:47 UTC, sblashkin requested changes

2020-09-18 16:47 UTC, sblashkin commented on src/index.js
> +      className="view-sources-arrow"
@yasodaesarapu, since we use BEM class name, should be view-sources__arrow

2020-09-18 16:47 UTC, sblashkin commented on src/index.js
>      viewsourceUrl: linkModel.isRequired,
@yasodaesarapu can you rename it to viewSourceUrl?

2020-09-18 16:51 UTC, sblashkin commented on src/index.js
> +    return ((isMobile && displayLightBox) || (!isMobile && hoverOnArrow)) && (
can you create a var for that condition? or even 2 vars for left and right part

2020-09-18 18:22 UTC, yasodaesarapu commented on src/index.js
> +    closeLightBox(this.toggleLightBox());
@MiSTERSPOONS Fixed

2020-09-18 18:22 UTC, yasodaesarapu commented on src/index.js
> +      className="view-sources-arrow"
@sblashkin Updated class name.

2020-09-18 18:23 UTC, yasodaesarapu commented on src/index.js
>      viewsourceUrl: linkModel.isRequired,
@sblashkin renamed.

2020-09-18 18:23 UTC, yasodaesarapu commented on src/index.js
> +    return ((isMobile && displayLightBox) || (!isMobile && hoverOnArrow)) && (
@sblashkin Created separate variables.

2020-09-18 18:39 UTC, yasodaesarapu commented on __tests__/src/index-test.js
> +    const viewSourceiconURL = 'https://images.everydayhealth.com/react-component-images/badge.png';
@wsaun-edh this is the icon we always use for this widget as of now. I just put it in props and default props, just in case we need to pass different icon in future.

2020-09-18 18:40 UTC, yasodaesarapu commented on __tests__/src/index-test.js
> +    wrapper.setState({ hoverOnArrow: true });
@wsaun-edh updated

2020-09-18 18:40 UTC, wsaun-edh approved these changes

2020-09-18 19:17 UTC, merged

2020-10-02 18:53 UTC, kzusy commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@evdy-consumer/component-react-in-text-citation/v/1.0.1)
- [GitHub release](https://github.com/evdy-consumer/component-react-in-text-citation/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: